### ISSUE TITLE
Different resolutions of screenshots depends on game

### ISSUE THREAD

**Issue by Master11250** [wiiu-env/ScreenshotWUPS#1]
In menu plugin works almost fine. Gamepad screenshot is perfect 854x480 while TV screenshot is 1280x720 resolution instead of 1920x1080.
In Breath of the wild plugin doesn't work. Nothing happens.
In Xenoblade Chronicles X plugin works. But resolutions of both screenshots is very low. Both in 640x360 instead of 854x480 in Gamepad and 1920x1080 in TV screenshot.

This will be perfect screenshot plugin if resolution problem will be solved. Choise of button combo is a great feature (I also wish that TV control button was be able to use but I don't think it's possible). I also suggest to introduce a mods -- which of screens to capture -- Gamepad, TV or both (I have a capture card so TV screenshot is not neccesary), it would save some wii u system resources if it's a problem.

**Comment by Maschell** [comment]
The screenshots are always taken at the native resolution, fixing it to a resolution would not increase the image quality at all.
Zelda simply doesn't have enough memory to properly take screenshots.

Adding options to choose the screen to be captured is something that could be implemented very easily. I'll try to include it into one of the next releases

**Comment by Master11250** [comment]
Got it.

**Comment by mariomadproductions** [comment]
For high-memory usage games, could the plugin use the sd card to store data temporarily rather than keeping it in memory?

**Comment by Maschell** [comment]
Screenshots can now be taken in much higher quality with #5
