### ISSUE TITLE
(Mario Kart 8) makes screenshots in most of the menus, but not in races.

### ISSUE THREAD

**Issue by LatteStarbuck** [wiiu-env/ScreenshotWUPS#12]
Title says, the plugin doesn't respond to the screenshot button combination when I'm in races, but it does in most of the menus such as the online game mode selection menu.

**Comment by Maschell** [comment]
At the moment the plugin only allows you to take screensshots when the home button is enabled

**Comment by Maschell** [comment]
Fixed with v0.1
