### ISSUE TITLE
[REQUEST] Create a gallery app to view screenshots 

### ISSUE THREAD

**Issue by matte-oss** [wiiu-env/ScreenshotWUPS#20]
Using wii u shell all the time to view screenshots is boring, it would be nice to have a gallery app to view screenshots
Sorry for my English

**Comment by TheMysteriousStar** [comment]
https://github.com/Xpl0itU/WiiUScreenshotManager/releases

**Comment by matte-oss** [comment]
Thank tou!

**Comment by matte-oss** [comment]
Thank you!
